services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-tracker-app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: unless-stopped

  tests:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    container_name: expense-tracker-playwright-tests
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./playwright-tests:/tests/source
      - ./playwright-report:/tests/playwright-report
      - ./test-results:/tests/test-results
    environment:
      - PLAYWRIGHT_BASE_URL=http://app:3000