# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master", "lesson22" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    env:
      BUILD_FOLDER: ./lesson18-playwright
      HEADLESS: true

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ env.BUILD_FOLDER }}/package-lock.json
    - name: Install dependencies
      working-directory: ${{ env.BUILD_FOLDER }}
      run: npm ci
    - name: Install Playwright browsers
      working-directory: ${{ env.BUILD_FOLDER }}
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: ${{ env.BUILD_FOLDER }}
      run: npx playwright test
    - name: Upload Playwright report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: ${{ env.BUILD_FOLDER }}/playwright-report/
        retention-days: 30